### PR TITLE
Fetch neighborhood and pobox details for address

### PR DESCRIPTION
**Pull request by sampatbadhe**
Fetch neighborhood and pobox details for address

Google Address with `neighborhood` and `pobox` details  👇 

```
<gd:structuredPostalAddress rel='http://schemas.google.com/g/2005#home'>
  <gd:formattedAddress>
    Manchester Square
    7
    Main street, Manchester, KY 40962
    US
  </gd:formattedAddress>

  <gd:street>Manchester Square</gd:street>
  <gd:pobox>7</gd:pobox>
  <gd:neighborhood>Main street</gd:neighborhood>
  <gd:city>Manchester</gd:city>
  <gd:region>Kentucky</gd:region>
  <gd:postcode>40962</gd:postcode>
  <gd:country>US</gd:country>
</gd:structuredPostalAddress>
```

### CODE REVIEW

**Comment by kyletolle** [comment]
Looks like that `#initialize` could benefit from some serious refactoring in the future.

**Comment by kyletolle** [comment]
Can we run Rubocop on these modified files?

**Comment by sampatbadhe** [comment]
> Looks like that #initialize could benefit from some serious refactoring in the future.

sure @kyletolle we will work on it later. 

>  Can we run Rubocop on these modified files?

Sue @kyletolle

**Comment by sampatbadhe** [comment]
@kyletolle 

Before & After rubocop stats for file - `lib/google-contacts/element.rb`

**Before** 👇 

`1 file inspected, 216 offenses detected`

**After** 👇 

`1 file inspected, 24 offenses detected`

**Review by rohandaxini — APPROVED** [review]

**Pull request merged**
