### PR TITLE
Set country from attributes of country

### PR DESCRIPTION
**Pull request by sampatbadhe**
Hello Team,

This PR handle's case to set details for country using `code` attribute

i.e.
`<gd:country code='US'></gd:country>` will set `country` as `US`
`<gd:country code='US'>USA</gd:country>` will set `country` as `USA`

Please review and advice.

Thanks

### CODE REVIEW

**Review by rohandaxini — APPROVED** [review]

**Comment by sampatbadhe** [comment]
@kyletolle & I had a discussion yesterday over the call and we agreed to return `code` for country if present and fallback to `label`(which is the full name) to keep the consistency. The `code` attribute here is used to pre-select country on Google contacts new UI.

i.e. 👇 

_**Following examples should return `US`, which is present in code attribute of `gd:country` tag.**_
- `<gd:country code='US'></gd:country>`
- `<gd:country code='US'>USA</gd:country>`
- `<gd:country code='US'>"United States</gd:country>`

_**Following examples should return text present inside the `gd:country` tag as `code` attribute is not present.**_ 
- `<gd:country>US</gd:country>`
- `<gd:country>USA</gd:country>`
- `<gd:country>"United States</gd:country>`

cc: @rohandaxini

**Comment by kyletolle** [comment]
@sampatbadhe Could we update the specs to have tests similar to what you said above? From reading the code/specs as-is, I can't really tell that the `@code` attribute should be the preferred country data and the text is the fallback.

**Comment by sampatbadhe** [comment]
@kyletolle 

Data Setup
> https://github.com/Kiprosh/google-contacts/pull/10/files#diff-f1813b2ffdd9b55e778c8435bb82c703R32

Test Case
> https://github.com/Kiprosh/google-contacts/pull/10/files#diff-39b91dd3d60bce34c6adba3837ba878bR145

**Comment by kyletolle** [comment]
@sampatbadhe The test case name of `#hashed_addresses` is not particularly meaningful. And the `it` validates an entire hash at once, which means that any piece of that data could be wrong and a spec named `#hashed_addresses` would fail without any real clear reason of why. For instance, if the spec failed because it returned 'USA' instead of 'US' we could see that the data was different but now what was wrong about it.

Here's an example of how I like to organize specs when there are multiple contexts to consider.
```ruby
context 'when the country text value exists' do
  context 'when the country code attribute exists' do
    let(:hashed_address) do
      # TODO: If we hashed the given address the same way, we could reuse this
      # let for all of the tests here.
    end
    let(:given_address) do
      # Use the Krypton address
    end
    let(:expected_country) { 'US' }

    it 'uses the country code attribute value' do
      # Validate just the Krypton address's country data
      expect(hashed_address[:country]).to eq(expected_country)
    end
  end

  context 'when the country code attribute is missing' do
    let(:hashed_address) do
      # TODO: If we hashed the given address the same way, we could reuse this
      # let for all of the tests here.
    end
    let(:given_address) do
      # Using the San Francisco address
    end
    let(:expected_country) { 'US' }

    it 'uses the country text value' do
      # Validate just the San Francisco address's country data
      expect(hashed_address[:country]).to eq(expected_country)
    end
end

context 'when the country text value is missing' do
  context 'when the country code attribute exists' do
    let(:hashed_address) do
      # TODO: If we hashed the given address the same way, we could reuse this
      # let for all of the tests here.
    end
    let(:given_address) do
      # Using the Finland address
    end
    let(:expected_country) { 'US' }

    it 'uses the country code attribute value' do
      # Validate just the Finland address's country data
      expect(hashed_address[:country]).to eq(expected_country)
    end
  end

  context 'when the country code attribute is missing' do
    let(:hashed_address) do
      # TODO: If we hashed the given address the same way, we could reuse this
      # let for all of the tests here.
    end
    let(:given_address) do
      # No existing test case for this one. Create one where country text and
      # code is blank.
    end
    let(:expected_country) { nil }

    it 'leaves the country code blank' do
      # Validate that the address's country data is `nil`
      expect(hashed_address[:country]).to eq(expected_country)
    end
  end
end
```

**Comment by kyletolle** [comment]
We could chat about this over a call too, so we could have an opportunity to actually write some code together and explore the topic some more!

**Comment by sampatbadhe** [comment]
Sure @kyletolle got your point :+1: I'll update the specs.

**Review by kyletolle — APPROVED** [review]
I had mentioned in https://github.com/Kiprosh/google-contacts/pull/10#issuecomment-453238320 how it would be nice to have more granular tests to better show that we are testing and why. @sampatbadhe made me aware that the current design of this code does not really allow for this. He's also created a PR at #11 that will help break out some of the code to make more granular tests more possible. Looking forward to iterating on that!

**Pull request merged**
